spring.application.name=rsvp
# ===============================
# Server
# ===============================
server.port=8080


# Google Sheets Configuration
google.sheets.spreadsheet-id=${GOOGLE_SHEET_ID}

# CORS (optional)
spring.web.cors.allowed-origins=*